services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=parentcaringservice'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=user'
    ports:
      - '15432:5432'
    volumes:
      - './init-db:/docker-entrypoint-initdb.d'
  redis:
    image: 'redis:latest'
    ports:
      - '16379:6379'
